CREATE TABLE ADDRESS_DETAILS(PUBLIC_SPACE VARCHAR(50) NOT NULL,HOUSE_NUMBER SMALLINT(6) NOT NULL, HOUSE_LETTER VARCHAR(4) ,HOUSE_NM_ADD VARCHAR(4),POSTCODE VARCHAR(10) NOT NULL,WOONPLATS VARCHAR(40) DEFAULT NULL,GEEMENTE VARCHAR(30) DEFAULT NULL,PROVINCE VARCHAR(20)  DEFAULT NULL,INDICATOR_NUM BIGINT,USAGE_PURPOSE VARCHAR(150),SURFACE_RES_OBJ INTEGER, RES_OBJ_STATUS VARCHAR(45),OBJECT_ID BIGINT,OBJECT_TYPE VARCHAR(3),SECONDARY_ADDRESS VARCHAR(1),CANDIDATE_ID BIGINT,PLEGE_STATUS VARCHAR(50),BUILD_YEAR INTEGER,X_NUM FLOAT(25,15),Y_NUM FLOAT(25,15),LANGITUDE FLOAT(25,15),LATTITUDE FLOAT(25,15), PRIMARY KEY(PUBLIC_SPACE ,HOUSE_NUMBER , HOUSE_LETTER  ,HOUSE_NM_ADD ,POSTCODE));

CREATE TABLE JOB_RUN_DETAIL(YEAR INTEGER, MONTH INTEGER,INSERTED INTEGER,UPDATED INTEGER,COMPLETEDTIME DATETIME DEFAULT CURRENT_TIMESTAMP);




